version: '3.4'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=evan
      - POSTGRES_PASSWORD=2842
      - POSTGRES_DB=shopapi
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_volume: